# Jekyll Defaults
title: Taehwa, KIM  
description: A small and simple site I made to test out Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://qupid-kth.github.io/"
github: http://github.com/QUPID-KTH/
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: CV
  url: /about/
- text: Research
  url: /research/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
https://github.com/QUPID-KTH/QUPID-KTH.github.io/blob/master/_config.yml
